# -*- coding: utf-8 -*-
{
    "name": "Vehicle Management System",
    "summary": """Manage your vehicle workshop or washing or repair and other services features with
                Multiple user profiles (workshop or service managers and mechanic users)
                Job cards with vehicle and service product like warrantyor guarantee
                Inspection of vehicle and add spare parts or componets with quotes
                Worksheet for repair or service of vehicles
                Multiple essential reports""",
    "description": """Workshop-Service-Wash-Repair Management""",
    'depends': ['sale_management', 'account', 'sale_stock', 'fleet', 'contacts', 'purchase', 'hr_attendance', 'odx_m2m_attachment_preview',
                'sale_car', 'pdc_payment', 'crm'],
    'author': 'Preciseways',
    'version': '15.0.0',
    'category': 'Industries',
    'sequence': -100000,

    "data": [
        #     'security/fleet_repair_security.xml',
        #     'security/ir_rule.xml',
            'security/ir.model.access.csv',
        'data/fleet_workshop_sequence.xml',
        #     'data/fleet_worksheet_sequence.xml',
        #     'wizard/fleet_workshop_assign_to_head_tech_view.xml',
        #     'wizard/fleet_inspection_assign_to_technician_view.xml',
        'wizard/fleet_advisor_nots_view.xml',
        'wizard/quality_check.xml',
        'views/fleet_workshop_view.xml',
        # 'views/purchase_task.xml',
        #     'views/fleet_inspection_view.xml',
        #     'views/fleet_worksheet_view.xml',
        'views/custom_sale_view.xml',
        'views/custom_purchase_view.xml',
        'views/res_partner.xml',
        'views/product.xml',
        'views/fleet_appointment_view.xml',
        'views/employee_viwes.xml',
        'views/fleet_quality.xml',
        'views/car_check.xml',
        'views/spear_check.xml',
        'views/paints_and_plumbing_check.xml',
        'views/purchase_requisition.xml',
        'views/stock_picking.xml',
        'views/sale_order_viwe.xml',
        'views/vehicle_view.xml',
        'views/crm_lead.xml',
        'views/time_to_work.xml',
        'views/available_technician.xml',
        'views/Job_controller.xml',
        'views/job_order_task.xml',
        # 'views/Job technician_state.xml',
        # 'views/quality_analysis.xml',
        # 'views/quality_analysis2.xml',
        'report/report_action.xml',
        #     'report/invoice_report.xml',
        #     'report/sale_order_report.xml',
        #     'report/fleet_workshop_label_view.xml',
        'report/fleet_workshop_receipt_view.xml',
        #     'report/fleet_inspection_request_report_view.xml',
        #     'report/fleet_inspection_result_report_view.xml',
        #     'report/fleet_worksheet_report_view.xml',
    ],
    'application': True,
    'installable': True,
    'license': 'OPL-1',
    'price': 50,
    'currency': 'EUR',
    'images': ['static/description/banner.png'],
}
